FROM node:20

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g wrangler@4.38.0   # 👈 instalar wrangler en la build
COPY . .

EXPOSE 8788

CMD ["wrangler", "pages", "dev", "public", "--local"]
