name = "pymeeyes-pages"
compatibility_date = "2025-09-17"


# Para desarrollo local con `wrangler pages dev`, puedes definir VARS no sensibles aquí.
# En producción (Pages), define **Environment Variables & Secrets** en el Dashboard.
[vars]
SESSION_TTL_SECONDS = 28800 # 8 horas
COOKIE_NAME = "auth"


# Secrets a definir en el Dashboard o con `wrangler secret put`:
# - ADMIN_USER
# - ADMIN_PW_HASH (SHA-256 hex de: password + PEPPER)
# - PEPPER (secreto adicional para derivación)
# - JWT_SECRET (clave HMAC para firmar JWT)